# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('youtube_video_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('SHORT', 'Short'), ('LONG_FORM', 'Long-form'), ('LIVE', 'Live'), ('PREMIERE', 'Premiere')], default='LONG_FORM', max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('PUBLIC_API', 'Public Data API'), ('ANALYTICS_API', 'YouTube Analytics API'), ('MANUAL', 'Entered manually')], max_length=20)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.BigIntegerField(blank=True, null=True)),
                ('impressions', models.BigIntegerField(blank=True, null=True)),
                ('impressions_ctr_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('watch_time_minutes', models.BigIntegerField(blank=True, null=True)),
                ('average_view_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_percentage_viewed', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('subscribers_gained', models.IntegerField(blank=True, null=True)),
                ('subscribers_lost', models.IntegerField(blank=True, null=True)),
                ('returning_viewers', models.BigIntegerField(blank=True, null=True)),
                ('unique_viewers', models.BigIntegerField(blank=True, null=True)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='youtube.video')),
            ],
            options={
                'db_table': 'video_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRetentionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elapsed_ratio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('audience_watch_ratio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('relative_retention_performance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_points', to='youtube.videosnapshot')),
            ],
            options={
                'db_table': 'video_retention_points',
                'ordering': ['elapsed_ratio'],
            },
        ),
        migrations.CreateModel(
            name='VideoTrafficSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=48)),
                ('views', models.BigIntegerField()),
                ('watch_time_minutes', models.BigIntegerField(blank=True, null=True)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='youtube.videosnapshot')),
            ],
            options={
                'db_table': 'video_traffic_sources',
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_channel_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('link_override_reason', models.TextField(blank=True, null=True)),
                ('channel_creation_date', models.DateField(blank=True, null=True)),
                ('niche', models.CharField(blank=True, max_length=160, null=True)),
                ('sub_niche', models.CharField(blank=True, max_length=160, null=True)),
                ('content_format', models.CharField(blank=True, max_length=160, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=300, null=True)),
                ('target_country', models.CharField(blank=True, max_length=120, null=True)),
                ('primary_language', models.CharField(blank=True, max_length=80, null=True)),
                ('content_type', models.CharField(choices=[('SHORTS', 'Shorts'), ('LONG_FORM', 'Long-form'), ('MIXED', 'Mixed')], default='MIXED', max_length=16)),
                ('upload_schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('ownership_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_brand_account', models.BooleanField(default=False)),
                ('monetization_status', models.CharField(choices=[('NOT_ELIGIBLE', 'Not Eligible'), ('IN_PROGRESS', 'In Progress'), ('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=24)),
                ('monetization_approved_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MONETIZED', 'Monetized'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('ABANDONED', 'Abandoned'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=24)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_upload_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='academy.student')),
            ],
            options={
                'db_table': 'youtube_channels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtube.youtubechannel'),
        ),
        migrations.CreateModel(
            name='SyncJobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('source', models.CharField(blank=True, choices=[('PUBLIC_API', 'Public Data API'), ('ANALYTICS_API', 'YouTube Analytics API'), ('MANUAL', 'Entered manually')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('quota_units_used', models.IntegerField(default=0)),
                ('items_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='youtube.youtubechannel')),
            ],
            options={
                'db_table': 'sync_job_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('PUBLIC_API', 'Public Data API'), ('ANALYTICS_API', 'YouTube Analytics API'), ('MANUAL', 'Entered manually')], max_length=20)),
                ('subscriber_count', models.BigIntegerField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('video_count', models.IntegerField(blank=True, null=True)),
                ('public_video_count', models.IntegerField(blank=True, null=True)),
                ('shorts_count', models.IntegerField(blank=True, null=True)),
                ('long_form_count', models.IntegerField(blank=True, null=True)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('watch_time_minutes', models.BigIntegerField(blank=True, null=True)),
                ('average_view_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_views_per_video', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('uploads_last_30_days', models.IntegerField(blank=True, null=True)),
                ('days_since_last_upload', models.IntegerField(blank=True, null=True)),
                ('channel_age_days', models.IntegerField(blank=True, null=True)),
                ('growth_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='youtube.youtubechannel')),
            ],
            options={
                'db_table': 'channel_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelOauthGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('encrypted_refresh_token', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('consent_version', models.CharField(max_length=40)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_grant', to='youtube.youtubechannel')),
            ],
            options={
                'db_table': 'channel_oauth_grants',
            },
        ),
        migrations.AddIndex(
            model_name='videosnapshot',
            index=models.Index(fields=['video', '-captured_at'], name='video_snaps_video_i_d12a66_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoretentionpoint',
            constraint=models.UniqueConstraint(fields=('snapshot', 'elapsed_ratio'), name='uniq_snapshot_elapsed_ratio'),
        ),
        migrations.AddConstraint(
            model_name='videotrafficsource',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_type'), name='uniq_snapshot_traffic_source'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['channel', '-published_at'], name='videos_channel_80a96d_idx'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('channel', 'youtube_video_id'), name='uniq_channel_video'),
        ),
        migrations.AddIndex(
            model_name='syncjobrun',
            index=models.Index(fields=['channel', '-started_at'], name='sync_job_ru_channel_3b8b11_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjobrun',
            index=models.Index(fields=['job_type', 'status'], name='sync_job_ru_job_typ_02fc98_idx'),
        ),
        migrations.AddIndex(
            model_name='channelsnapshot',
            index=models.Index(fields=['channel', '-captured_at'], name='channel_sna_channel_0104c9_idx'),
        ),
    ]
