# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_SIGNED', 'Partially Signed'), ('SIGNED', 'Signed'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=24)),
                ('content', models.JSONField()),
                ('template_version', models.CharField(max_length=40)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='completion/%Y/')),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to='academy.student')),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='completion.completionrecord')),
            ],
            options={
                'db_table': 'completion_records',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('INSTRUCTOR_CONDUCT', 'Instructor Conduct'), ('PLATFORM_ACCESS', 'Platform Access'), ('BILLING', 'Billing'), ('EVALUATION_DISPUTE', 'Evaluation Dispute'), ('HARASSMENT', 'Harassment'), ('OTHER', 'Other')], max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('APPEALED', 'Appealed')], db_index=True, default='SUBMITTED', max_length=24)),
                ('academy_response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_outcome', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_grievances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='academy.student')),
            ],
            options={
                'db_table': 'grievances',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='grievances/%Y/%m/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='completion.grievance')),
            ],
            options={
                'db_table': 'grievance_attachments',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_role', models.CharField(choices=[('STUDENT', 'Student'), ('INSTRUCTOR', 'Instructor'), ('ACADEMY_REPRESENTATIVE', 'Academy Representative')], max_length=32)),
                ('signer_name', models.CharField(max_length=160)),
                ('signature_image_url', models.TextField(blank=True, null=True)),
                ('signature_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('completion_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='completion.completionrecord')),
                ('signer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INSTRUCTOR_FEEDBACK', 'Instructor Feedback'), ('WARNING_NOTICE', 'Warning Notice'), ('PERFORMANCE_MEETING', 'Performance Meeting'), ('MISSED_DEADLINE', 'Missed Deadline'), ('SUPPORT_REQUEST', 'Support Request'), ('ACTION_PLAN', 'Action Plan')], max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='academy.student')),
            ],
            options={
                'db_table': 'communication_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['student', '-occurred_at'], name='communicati_student_ff6631_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='completionrecord',
            constraint=models.UniqueConstraint(fields=('student', 'version'), name='uniq_completion_student_version'),
        ),
        migrations.AddConstraint(
            model_name='signature',
            constraint=models.UniqueConstraint(fields=('completion_record', 'signer_role'), name='uniq_signature_record_role'),
        ),
    ]
