# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(help_text='Human-facing code, e.g. YTA-2026-01.', max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='PLANNED', max_length=20)),
                ('research_days', models.PositiveIntegerField(blank=True, help_text='Per-batch override of the academy research window. Blank uses the global setting.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'batches',
                'ordering': ['status', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enrollment_id', models.CharField(db_index=True, help_text='Generated. PREFIX-YYYY-NNNN.', max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('guardian_name', models.CharField(blank=True, max_length=160, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('enrollment_date', models.DateField()),
                ('course_start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('research_start_date', models.DateField(blank=True, null=True)),
                ('research_deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('roadmap_stage', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('NICHE_RESEARCH', 'Niche Research'), ('ASSIGNMENT_SUBMISSION', 'Assignment Submission'), ('ASSIGNMENT_REVIEW', 'Assignment Review'), ('RESEARCH_APPROVED', 'Research Approved'), ('CHANNEL_CREATION', 'Channel Creation'), ('CONTENT_PRODUCTION', 'Content Production'), ('PERFORMANCE_MONITORING', 'Performance Monitoring'), ('BATCH_COMPLETION', 'Batch Completion')], db_index=True, default='ENROLLMENT', max_length=32)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('RESEARCH_PENDING', 'Research Pending'), ('RESEARCH_IN_PROGRESS', 'Research in Progress'), ('ASSIGNMENT_SUBMITTED', 'Assignment Submitted'), ('REVISION_REQUIRED', 'Revision Required'), ('RESEARCH_APPROVED', 'Research Approved'), ('CHANNEL_CREATION_PENDING', 'Channel Creation Pending'), ('CHANNEL_CREATED', 'Channel Created'), ('CONTENT_PRODUCTION_STARTED', 'Content Production Started'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('AT_RISK', 'At Risk'), ('BATCH_COMPLETED', 'Batch Completed'), ('DROPPED_OUT', 'Dropped Out'), ('SUSPENDED', 'Suspended')], db_index=True, default='ENROLLED', max_length=32)),
                ('lms_student_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agreement_status', models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('ISSUED', 'Issued'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('SUPERSEDED', 'Superseded')], default='NOT_ISSUED', max_length=24)),
                ('completion_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_SIGNED', 'Partially Signed'), ('SIGNED', 'Signed'), ('SUPERSEDED', 'Superseded')], max_length=24, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-enrollment_date', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('AGREEMENT', 'Agreement'), ('CERTIFICATE', 'Certificate'), ('RESEARCH_FILE', 'Research File'), ('SCREENSHOT', 'Screenshot'), ('SPREADSHEET', 'Spreadsheet'), ('PROFILE_IMAGE', 'Profile Image'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='student-documents/%Y/%m/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('ENROLLED', 'Enrolled'), ('RESEARCH_PENDING', 'Research Pending'), ('RESEARCH_IN_PROGRESS', 'Research in Progress'), ('ASSIGNMENT_SUBMITTED', 'Assignment Submitted'), ('REVISION_REQUIRED', 'Revision Required'), ('RESEARCH_APPROVED', 'Research Approved'), ('CHANNEL_CREATION_PENDING', 'Channel Creation Pending'), ('CHANNEL_CREATED', 'Channel Created'), ('CONTENT_PRODUCTION_STARTED', 'Content Production Started'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('AT_RISK', 'At Risk'), ('BATCH_COMPLETED', 'Batch Completed'), ('DROPPED_OUT', 'Dropped Out'), ('SUSPENDED', 'Suspended')], max_length=32, null=True)),
                ('to_status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('RESEARCH_PENDING', 'Research Pending'), ('RESEARCH_IN_PROGRESS', 'Research in Progress'), ('ASSIGNMENT_SUBMITTED', 'Assignment Submitted'), ('REVISION_REQUIRED', 'Revision Required'), ('RESEARCH_APPROVED', 'Research Approved'), ('CHANNEL_CREATION_PENDING', 'Channel Creation Pending'), ('CHANNEL_CREATED', 'Channel Created'), ('CONTENT_PRODUCTION_STARTED', 'Content Production Started'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('AT_RISK', 'At Risk'), ('BATCH_COMPLETED', 'Batch Completed'), ('DROPPED_OUT', 'Dropped Out'), ('SUSPENDED', 'Suspended')], max_length=32)),
                ('from_stage', models.CharField(blank=True, choices=[('ENROLLMENT', 'Enrollment'), ('NICHE_RESEARCH', 'Niche Research'), ('ASSIGNMENT_SUBMISSION', 'Assignment Submission'), ('ASSIGNMENT_REVIEW', 'Assignment Review'), ('RESEARCH_APPROVED', 'Research Approved'), ('CHANNEL_CREATION', 'Channel Creation'), ('CONTENT_PRODUCTION', 'Content Production'), ('PERFORMANCE_MONITORING', 'Performance Monitoring'), ('BATCH_COMPLETION', 'Batch Completion')], max_length=32, null=True)),
                ('to_stage', models.CharField(blank=True, choices=[('ENROLLMENT', 'Enrollment'), ('NICHE_RESEARCH', 'Niche Research'), ('ASSIGNMENT_SUBMISSION', 'Assignment Submission'), ('ASSIGNMENT_REVIEW', 'Assignment Review'), ('RESEARCH_APPROVED', 'Research Approved'), ('CHANNEL_CREATION', 'Channel Creation'), ('CONTENT_PRODUCTION', 'Content Production'), ('PERFORMANCE_MONITORING', 'Performance Monitoring'), ('BATCH_COMPLETION', 'Batch Completion')], max_length=32, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'student status history',
                'db_table': 'student_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
