# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='criteria_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='research.researchcriteriaset'),
        ),
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academy.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academy.student'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentstatushistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='academy.student'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch', 'status'], name='students_batch_i_4dbe74_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['instructor'], name='students_instruc_a9994b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['research_deadline'], name='students_researc_0ea12f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentstatushistory',
            index=models.Index(fields=['student', '-created_at'], name='student_sta_student_55a113_idx'),
        ),
    ]
