# Generated by Django 6.1.1 on 2026-09-25 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Signed in"),
                            ("RESEARCH_DRAFT_SAVED", "Research draft saved"),
                            ("RESEARCH_SUBMITTED", "Research submitted"),
                            ("ASSIGNMENT_SUBMITTED", "Assignment submitted"),
                            ("CHANNEL_CONNECTED", "Channel analytics connected"),
                            ("VIDEO_PUBLISHED", "Video published"),
                            ("CLASS_ATTENDED", "Attended a class"),
                            ("MENTOR_SESSION", "Mentoring session"),
                            ("RESEARCH_REVIEWED", "Research reviewed"),
                            ("ASSIGNMENT_REVIEWED", "Assignment reviewed"),
                            ("STATUS_CHANGED", "Status changed"),
                            ("CHANNEL_ADDED", "Channel recorded"),
                            ("CLASS_MISSED", "Missed a class"),
                            ("CONTACT", "Contacted by staff"),
                            ("NOTE", "Staff note"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("detail", models.TextField(blank=True, null=True)),
                ("is_student_action", models.BooleanField(default=False)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64, null=True)),
                ("target_id", models.CharField(blank=True, max_length=64, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="academy.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "student activities",
                "db_table": "student_activities",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-occurred_at"],
                        name="student_act_student_d3550d_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="student_act_target__71206d_idx",
                    ),
                ],
            },
        ),
    ]
