# Generated by Django 6.1.1 on 2026-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_studentactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Signed in"),
                    ("RESEARCH_DRAFT_SAVED", "Research draft saved"),
                    ("RESEARCH_SUBMITTED", "Research submitted"),
                    ("ASSIGNMENT_SUBMITTED", "Assignment submitted"),
                    ("CHANNEL_CONNECTED", "Channel analytics connected"),
                    ("CHANNEL_SUBMITTED", "Channel submitted for review"),
                    ("VIDEO_PUBLISHED", "Video published"),
                    ("CLASS_ATTENDED", "Attended a class"),
                    ("MENTOR_SESSION", "Mentoring session"),
                    ("RESEARCH_REVIEWED", "Research reviewed"),
                    ("ASSIGNMENT_REVIEWED", "Assignment reviewed"),
                    ("STATUS_CHANGED", "Status changed"),
                    ("CHANNEL_ADDED", "Channel recorded"),
                    ("CLASS_MISSED", "Missed a class"),
                    ("CONTACT", "Contacted by staff"),
                    ("NOTE", "Staff note"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
