# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('youtube', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.JSONField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('channels', models.JSONField(default=list)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('cooldown_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ScoringFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('requires_analytics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scoring_factors',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored'), ('ESCALATED', 'Escalated')], db_index=True, default='NEW', max_length=16)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='academy.batch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='academy.student')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.alertrule')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['status', '-priority', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('delivery_detail', models.TextField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitoring.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('band', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('AT_RISK', 'At Risk'), ('UNSATISFACTORY', 'Unsatisfactory')], db_index=True, max_length=24)),
                ('breakdown', models.JSONField()),
                ('excluded_factors', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_automated', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academy.student')),
            ],
            options={
                'db_table': 'performance_evaluations',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('BATCH', 'Batch'), ('STUDENT', 'Student'), ('CHANNEL', 'Channel')], max_length=16)),
                ('scope_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metric', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('comparator', models.CharField(choices=[('GTE', 'At least'), ('LTE', 'At most'), ('EQ', 'Exactly'), ('WITHIN_DAYS', 'Within days')], max_length=16)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
                ('window_days', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_analytics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'performance_targets',
                'indexes': [models.Index(fields=['scope', 'scope_id'], name='performance_scope_4d35d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TargetResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('BEHIND_SCHEDULE', 'Behind Schedule'), ('TARGET_ACHIEVED', 'Target Achieved'), ('TARGET_MISSED', 'Target Missed'), ('AT_RISK', 'At Risk'), ('NOT_ENOUGH_DATA', 'Not Enough Data')], db_index=True, max_length=24)),
                ('instructor_comment', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_results', to='youtube.youtubechannel')),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_comments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_results', to='academy.student')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.performancetarget')),
            ],
            options={
                'db_table': 'target_results',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'priority'], name='alerts_status_976bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['assigned_to', 'status'], name='alerts_assigne_ef25da_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['dedupe_key', '-detected_at'], name='alerts_dedupe__a331e7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_6c7360_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivery_status'], name='notificatio_deliver_3684d5_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluation',
            index=models.Index(fields=['student', '-computed_at'], name='performance_student_64cc99_idx'),
        ),
        migrations.AddIndex(
            model_name='targetresult',
            index=models.Index(fields=['target', '-evaluated_at'], name='target_resu_target__a2afe6_idx'),
        ),
    ]
