# Generated by Django 6.1.1 on 2026-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="response_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="submission_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
