# Generated by Django 6.0.7 on 2026-08-02 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCriteriaSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'research_criteria_sets',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_criteria_set_name_version')],
            },
        ),
        migrations.CreateModel(
            name='ResearchCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_passing_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('is_required', models.BooleanField(default=True, help_text='Failing a required criterion fails the submission.')),
                ('evidence_required', models.BooleanField(default=False)),
                ('evaluator_notes', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('criteria_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='research.researchcriteriaset')),
            ],
            options={
                'verbose_name_plural': 'research criteria',
                'db_table': 'research_criteria',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('RESUBMITTED', 'Resubmitted'), ('OVERDUE', 'Overdue')], db_index=True, default='DRAFT', max_length=24)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('niche', models.CharField(blank=True, max_length=160, null=True)),
                ('sub_niche', models.CharField(blank=True, max_length=160, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=300, null=True)),
                ('target_country', models.CharField(blank=True, max_length=120, null=True)),
                ('content_format', models.CharField(blank=True, max_length=160, null=True)),
                ('video_length_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_frequency', models.CharField(blank=True, max_length=160, null=True)),
                ('competition_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=16, null=True)),
                ('earning_potential', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=16, null=True)),
                ('keyword_research', models.TextField(blank=True, null=True)),
                ('content_gap_analysis', models.TextField(blank=True, null=True)),
                ('monetization_potential', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_research', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_submissions', to='academy.student')),
            ],
            options={
                'db_table': 'research_submissions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCriterionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passed', models.BooleanField()),
                ('evaluator_note', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='research.researchcriterion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='research.researchsubmission')),
            ],
            options={
                'db_table': 'research_criterion_scores',
            },
        ),
        migrations.CreateModel(
            name='ResearchCompetitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.URLField(max_length=500)),
                ('subscriber_count', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='research.researchsubmission')),
            ],
            options={
                'db_table': 'research_competitors',
            },
        ),
        migrations.CreateModel(
            name='ResearchAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('AGREEMENT', 'Agreement'), ('CERTIFICATE', 'Certificate'), ('RESEARCH_FILE', 'Research File'), ('SCREENSHOT', 'Screenshot'), ('SPREADSHEET', 'Spreadsheet'), ('PROFILE_IMAGE', 'Profile Image'), ('OTHER', 'Other')], default='RESEARCH_FILE', max_length=24)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='research/%Y/%m/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='research.researchsubmission')),
            ],
            options={
                'db_table': 'research_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='researchsubmission',
            index=models.Index(fields=['student', '-created_at'], name='research_su_student_ea32ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'version'), name='uniq_research_student_version'),
        ),
        migrations.AddConstraint(
            model_name='researchcriterionscore',
            constraint=models.UniqueConstraint(fields=('submission', 'criterion'), name='uniq_score_submission_criterion'),
        ),
    ]
