# Generated by Django 6.0.7 on 2026-08-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcompetitor',
            name='metrics_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='metrics_source',
            field=models.CharField(blank=True, choices=[('PUBLIC_API', 'Public Data API'), ('ANALYTICS_API', 'YouTube Analytics API'), ('MANUAL', 'Entered manually')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='newest_video_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='oldest_video_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='video_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='video_views_series',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='view_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchcompetitor',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
