# Generated by Django 6.1.1 on 2026-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_researchcompetitor_metrics_fetched_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchsubmission",
            name="channel_sheet",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
